export const themes = {
  pink: {
    name: 'Pink',
    background: '#fff0f5',
    primary: '#ff4d85',
    secondary: '#ff99b3',
    card: '#fff',
    cardCompleted: '#ffb3c6',
    iconBackground: '#ffe6f0',
    iconBackgroundCompleted: '#ff4d85',
    text: '#333',
    textCompleted: '#fff',
    border: '#ffe6f0',
    borderCompleted: '#ff99b3',
  },
  lavender: {
    name: 'Lavender',
    background: '#f3e8ff',
    primary: '#9333ea',
    secondary: '#c084fc',
    card: '#fff',
    cardCompleted: '#d8b4fe',
    iconBackground: '#f3e8ff',
    iconBackgroundCompleted: '#9333ea',
    text: '#333',
    textCompleted: '#fff',
    border: '#f3e8ff',
    borderCompleted: '#c084fc',
  },
  mint: {
    name: 'Mint',
    background: '#ecfdf5',
    primary: '#10b981',
    secondary: '#34d399',
    card: '#fff',
    cardCompleted: '#a7f3d0',
    iconBackground: '#ecfdf5',
    iconBackgroundCompleted: '#10b981',
    text: '#333',
    textCompleted: '#fff',
    border: '#ecfdf5',
    borderCompleted: '#34d399',
  },
  peach: {
    name: 'Peach',
    background: '#fff1f2',
    primary: '#f43f5e',
    secondary: '#fb7185',
    card: '#fff',
    cardCompleted: '#fecdd3',
    iconBackground: '#fff1f2',
    iconBackgroundCompleted: '#f43f5e',
    text: '#333',
    textCompleted: '#fff',
    border: '#fff1f2',
    borderCompleted: '#fb7185',
  }
};
